---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-gradle-
spec:
  pipelineRef:
    name: java-demo-pipeline
  params:
    - name: repo_url
      value: https://github.com/pramodbindal/java-demo.git
    - name: revision
      value: main
    - name: registry
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/gradle
    - name: buildCommand
      value: "./gradlew -g ${LOCAL_CACHE_REPO} build"
    - name: cachePatterns
      value: [ "**.gradle" ]
    - name: image
      value: gradle
  workspaces:
    - name: source
      emptyDir: {}
