---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pipelinerun-mvn-
spec:
  pipelineRef:
    name: java-demo-pipeline
  params:
    - name: repo_url
      value: https://github.com/pramodbindal/java-demo.git
    - name: revision
      value: main
    - name: registry
      value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/mvn
    - name: buildCommand
      value: "./mvnw -Dmaven.repo.local=${MVN_LOCAL_REPO} install"
    - name: cachePatterns
      value: [ "**pom.xml" ]
    - name: image
      value: openjdk:latest
  workspaces:
    - name: source
      emptyDir: {}
